# MoveIt controller interfaces
controller_list:
  - name: left_arm/$(arg scaled_joint_traj_controller_name)
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
  - name: right_arm/$(arg scaled_joint_traj_controller_name)
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint

  $(arg left_gripper_onrobot_comment)- name: left_gripper/gripper_controller
  $(arg left_gripper_onrobot_comment)  action_ns: gripper_cmd
  $(arg left_gripper_onrobot_comment)  default: true
  $(arg left_gripper_onrobot_comment)  type: GripperCommand
  $(arg left_gripper_onrobot_comment)  allow_failure: true
  $(arg left_gripper_onrobot_comment)  joints:
  $(arg left_gripper_onrobot_comment)    - left_gripper_joint
  $(arg left_gripper_onrobot_comment)    - left_gripper_mirror_joint

  $(arg right_gripper_onrobot_comment)- name: right_gripper/gripper_controller
  $(arg right_gripper_onrobot_comment)  action_ns: gripper_cmd
  $(arg right_gripper_onrobot_comment)  default: true
  $(arg right_gripper_onrobot_comment)  type: GripperCommand
  $(arg right_gripper_onrobot_comment)  allow_failure: true
  $(arg right_gripper_onrobot_comment)  joints:
  $(arg right_gripper_onrobot_comment)    - right_gripper_joint
  $(arg right_gripper_onrobot_comment)    - right_gripper_mirror_joint